- hosts: localhost
  gather_facts: False

  tasks:

    - name: Launching a slave VM (EC2 instance)
      ec2:
         aws_access_key: "{{aws_access_key}}"
         aws_secret_key: "{{aws_secret_key}}"
         region: us-east-2
         key_name: "Main VM SSH Credentials"
         group: global-access-security-group
         instance_type: t2.micro
         image: "ami-0d5d9d301c853a04a"
         wait: yes
         #state: 'running'
         exact_count: 1
         count_tag:
            Name: slave
         instance_tags:
            Name: slave
         
      register: slave_ec2
      
    
    -  debug:
          msg: "{{ slave_ec2 }}"
         #msg: "{{ slave_ec2['ansible_facts']['ansible_ec2_public_ipv4'] }}"
    
    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      loop: "{{ slave_ec2.instances }}"
    - name: install python module
      command: python3 -m pip install requests

 

#- hosts: ec2hosts
#  name: configuration play
#  user: ec2-user
#  gather_facts: true
#
#  tasks:
#
#     - name: Check NTP service
#       service: name=ntpd state=started
