- hosts: localhost
  gather_facts: False

  tasks:

    - name: Launching a slave VM (EC2 instance)
      ec2:
         aws_access_key: "{{aws_access_key}}"
         aws_secret_key: "{{aws_secret_key}}"
         region: us-east-2
         key_name: "Slave VM SSH Credentials"
         group: global-access-security-group
         instance_type: t2.micro
         image: "ami-0d5d9d301c853a04a"
         wait: yes
         #state: 'running'
         exact_count: 1
         count_tag:
            Name: slave
         instance_tags:
            Name: slave
         
      register: slave_ec2
      
    
    -  debug:
          msg: "{{ slave_ec2.instances[0].public_ip }}"